[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "multimodal-stimulus-fmri-prediction"
version = "0.0.1"
authors = [
]
description = "Description"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [ "numpy",
  "librosa",
  "moviepy",
  "tqdm",
  "h5py",
  "pandas",        # for transcript handling later
  "opencv-python",  # for video info reading
  "moviepy==1.0.3"
  ]

[project.urls]
Homepage = ""
Issues = ""